fixed
Error: Attribute maxlength is only allowed when the input type is email, password, search, tel, text, or url.

From line 154, column 10; to line 156, column 92

↩         <input class="input is-primary" type="number" name="bod"↩                                           id="bod" placeholder="&euro;45.00               " maxlength="50" minlength="5" required↩                                           oninput="checkBodAmount()" step="0.01" disabled >

Error: Attribute minlength is only allowed when the input type is email, password, search, tel, text, or url.

From line 154, column 10; to line 156, column 92

↩         <input class="input is-primary" type="number" name="bod"↩                                           id="bod" placeholder="&euro;45.00               " maxlength="50" minlength="5" required↩                                           oninput="checkBodAmount()" step="0.01" disabled >